from flask import Flask,send_from_directory,render_template
from flask_restful import Resource, Api
from package.patient import Patients, Patient
from package.doctor import Doctors, Doctor
from package.appointment import Appointments, Appointment
from package.common import Common
import json
from flask import request, jsonify
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from flask import Flask, render_template, request

with open('HMS\config.json') as data_file:
    config = json.load(data_file)

app = Flask(__name__, static_url_path='')
api = Api(app)

api.add_resource(Patients, '/patient')
api.add_resource(Patient, '/patient/<int:id>')
api.add_resource(Doctors, '/doctor')
api.add_resource(Doctor, '/doctor/<int:id>')
api.add_resource(Appointments, '/appointment')
api.add_resource(Appointment, '/appointment/<int:id>')
api.add_resource(Common, '/common')


@app.route('/')
def index():
    return app.send_static_file('login.html')

@app.route('/home', methods=['POST'])
def home():
    return app.send_static_file('index.html')

patients = {}

@app.route('/create_patient', methods=['POST'])
def create_patient():
    if request.method == 'POST':
        data = request.json
        # Assuming data contains patient name and email
        patient_name = data.get('name')
        patient_email = data.get('email')

        # Storing patient name and email in a dictionary
        patient_id = len(patients) + 1
        patients[patient_id] = {'name': patient_name, 'email': patient_email}

        # return a response if needed
        print(patients)
        return jsonify({'message': 'Patient created successfully', 'patient_id': patient_id})


@app.route('/create_appointment', methods=['POST'])
def create_appointment():
    if request.method == 'POST':
        # Assuming you receive appointment data in JSON format
        data = request.json

        # Extract appointment details from the JSON data
        doctor = data.get('doctor')
        patient = data.get('patient')
        appointment_date = data.get('appointmentDate')
# Retrieve patient's email from the dictionary using patient's name
        patient_name = patient.split()[0]
        print(patient_name)
        # Initialize patient_email as None
        patient_email = None
        print(patients)
        # Iterate through patients dictionary to find matching patient name
        for patient_id, patient_info in patients.items():
            print(patient_id)
            if patient_info['name'] == patient_name:
                patient_email = patient_info['email']
                break

        # If patient_email is still None, patient not found in the dictionary
        if patient_email is None:
            return jsonify({'error': 'Patient not found in the system'}), 404

        # After creating the appointment, send the email notification
        sender_email = 'juanosebastian111@gmail.com'
        receiver_email = patient_email
        subject = 'Hospital Appointment'
        body = f'Dear {patient},\n\nHope this email finds you well.\nThis is an autogenerated mail to confirm your upcoming appointment scheduled on {appointment_date}.\n\nAppointment Details:\nDate and Time: {appointment_date}\nDoctor: {doctor}\n\nThank you for choosing us. Look forward for the appointment.\n\nBest regards,\nHMS'

        try:
            smtp_server = smtplib.SMTP('smtp.gmail.com', 587)
            smtp_server.starttls()
            smtp_server.login('juanosebastian111@gmail.com', 'nuxd zqgs mlhd kffp')  # Use your Gmail email and App Password
            smtp_server.sendmail(sender_email, receiver_email, f'Subject: {subject}\n\n{body}')
            smtp_server.quit()
            return jsonify({'message': 'Appointment created successfully and email sent'})
        except Exception as e:
            return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True,host=config['host'],port=config['port'])